### ISSUE TITLE
Home folder structure improvements

### ISSUE THREAD

**Issue by different-name** [different-name/nix-files#20]
There's probably a better way to add packages than keeping a list of `home.packages` in `home/global/default.nix`
Perhaps they should be added to the default.nix files in the global folder?
This would help split up the general persistence.nix file as well

**Comment by Different-Name** [comment]
I don't want to split up the persistence.nix as mentioned, maybe i'll make a module that takes a list of sets in the following format, instead of having home.packages

```nix
[
  {
    package = pkgs.vesktop;
    folders = [
      ".config/vesktop"
    ];
  }
  {
    package = pkgs.unityhub;
    folders = [
      ".config/unityhub"
      ".config/unity3d"
    ];
  }
];

```

**Comment by different-name** [comment]
Took a different approach in #56
