### ISSUE TITLE
Default allow restore token for screencasting

### ISSUE THREAD

**Issue by different-name** [different-name/nix-files#41]

**Comment by Different-Name** [comment]
https://www.github.com/Vencord/Vesktop/issues/583

**Comment by Different-Name** [comment]
Created an issue upstream https://issues.chromium.org/issues/354537406

**Comment by Different-Name** [comment]
https://www.github.com/Vencord/Vesktop/issues/583#issuecomment-2244544001

I should find a way to default `allow restore token` if possible, as I will end up clicking it every time otherwise

**Comment by different-name** [comment]
Should make an MR for this functionality, allow for all or specific applications to default to on, as specific in config

Related issue:
https://www.github.com/hyprwm/xdg-desktop-portal-hyprland/issues/11

**Comment by different-name** [comment]
https://github.com/hyprwm/xdg-desktop-portal-hyprland/releases/tag/v1.3.5

Allow restore token has a default option now
