### ISSUE TITLE
Random audio spikes

### ISSUE THREAD

**Issue by different-name** [different-name/nix-files#7]
Random audio spikes seem to sometimes occur when playing games, noticed most often when playing Spin Rhythm, occurred once while playing once human, and I believe while on the desktop with nothing playing, though I am not sure

**Comment by Different-Name** [comment]
Issue seems to have gone away, perhaps with updates upstream

**Comment by Different-Name** [comment]
Occurs when streaming on vesktop, not sure if it occurs on other apps

**Comment by Different-Name** [comment]
Opened an issue on vesktop repo (#772)

**Comment by different-name** [comment]
Closing this in favour of upstream issue
